# Generated by Django 5.2.6 on 2025-09-09 00:57

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_categoria_noticia_activo_alter_noticia_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='contenido',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
