# Generated by Django 5.2.6 on 2025-09-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_noticia_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='categoria',
            field=models.CharField(max_length=20, verbose_name='Categoria'),
        ),
    ]
