# Generated by Django 5.2.6 on 2025-09-09 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='apellidoM',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellidoP',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='edad',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='edad'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre'),
        ),
    ]
