# Generated by Django 5.2.6 on 2025-09-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_apellidom_alter_usuario_apellidop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_perfil'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='mensaje',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Algo sobre ti'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('admin', 'administrador'), ('editor', 'Editor'), ('normal', 'Normal')], default='normal', max_length=20),
        ),
    ]
