# Generated by Django 5.2.6 on 2025-09-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_foto_usuario_mensaje_usuario_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('admin', 'Administrador'), ('editor', 'Editor'), ('normal', 'Normal')], default='normal', max_length=20),
        ),
    ]
